export enum ReportReasonCode {
  FAKE_LISTING = 'FAKE_LISTING',
  SCAM = 'SCAM',
  ALREADY_SOLD = 'ALREADY_SOLD',
  WRONG_INFORMATION = 'WRONG_INFORMATION',
  DUPLICATE = 'DUPLICATE',
  OFFENSIVE = 'OFFENSIVE',
  OTHER = 'OTHER',
}
