export enum RejectionReasonCode {
  FAKE_LISTING = 'FAKE_LISTING',
  DUPLICATE = 'DUPLICATE',
  WRONG_CATEGORY = 'WRONG_CATEGORY',
  POOR_PHOTOS = 'POOR_PHOTOS',
  PRICE_MISMATCH = 'PRICE_MISMATCH',
  OTHER = 'OTHER',
}
