/**
 * Bangladesh's administrative tree: 8 divisions, 64 districts, and the
 * upazilas plus metropolitan thanas under them. The platform only serves
 * Bangladesh, so this ships as data rather than coming from an API — the
 * listing form's cascade and the server-side check of what it submits both
 * read from here.
 *
 * Generated; edit the source list rather than patching entries by hand.
 */
export interface BdDistrict {
  name: string;
  thanas: string[];
}

export interface BdDivision {
  name: string;
  districts: BdDistrict[];
}

export const BD_DIVISIONS: BdDivision[] = [
  {
    name: "Barishal",
    districts: [
      {
        name: "Barguna",
        thanas: [
          "Amtali",
          "Bamna",
          "Barguna Sadar",
          "Betagi",
          "Patharghata",
          "Taltali",
        ],
      },
      {
        name: "Barishal",
        thanas: [
          "Agailjhara",
          "Airport",
          "Babuganj",
          "Bakerganj",
          "Banaripara",
          "Bandar",
          "Barishal Kotwali",
          "Barishal Sadar",
          "Gaurnadi",
          "Hizla",
          "Kawnia",
          "Mehendiganj",
          "Muladi",
          "Wazirpur",
        ],
      },
      {
        name: "Bhola",
        thanas: [
          "Bhola Sadar",
          "Burhanuddin",
          "Char Fasson",
          "Daulatkhan",
          "Lalmohan",
          "Manpura",
          "Tazumuddin",
        ],
      },
      {
        name: "Jhalokati",
        thanas: [
          "Jhalokati Sadar",
          "Kathalia",
          "Nalchity",
          "Rajapur",
        ],
      },
      {
        name: "Patuakhali",
        thanas: [
          "Bauphal",
          "Dashmina",
          "Dumki",
          "Galachipa",
          "Kalapara",
          "Mirzaganj",
          "Patuakhali Sadar",
          "Rangabali",
        ],
      },
      {
        name: "Pirojpur",
        thanas: [
          "Bhandaria",
          "Kawkhali",
          "Mathbaria",
          "Nazirpur",
          "Nesarabad",
          "Pirojpur Sadar",
          "Zianagar",
        ],
      },
    ],
  },
  {
    name: "Chattogram",
    districts: [
      {
        name: "Bandarban",
        thanas: [
          "Alikadam",
          "Bandarban Sadar",
          "Lama",
          "Naikhongchhari",
          "Rowangchhari",
          "Ruma",
          "Thanchi",
        ],
      },
      {
        name: "Brahmanbaria",
        thanas: [
          "Akhaura",
          "Ashuganj",
          "Bancharampur",
          "Bijoynagar",
          "Brahmanbaria Sadar",
          "Kasba",
          "Nabinagar",
          "Nasirnagar",
          "Sarail",
        ],
      },
      {
        name: "Chandpur",
        thanas: [
          "Chandpur Sadar",
          "Faridganj",
          "Haimchar",
          "Haziganj",
          "Kachua",
          "Matlab Dakshin",
          "Matlab Uttar",
          "Shahrasti",
        ],
      },
      {
        name: "Chattogram",
        thanas: [
          "Akbarshah",
          "Anwara",
          "Bakalia",
          "Bandar",
          "Banshkhali",
          "Bayezid Bostami",
          "Boalkhali",
          "Chandanaish",
          "Chandgaon",
          "Chawkbazar",
          "Double Mooring",
          "EPZ",
          "Fatikchhari",
          "Halishahar",
          "Hathazari",
          "Khulshi",
          "Kotwali",
          "Lohagara",
          "Mirsharai",
          "Pahartali",
          "Panchlaish",
          "Patenga",
          "Patiya",
          "Rangunia",
          "Raozan",
          "Sadarghat",
          "Sandwip",
          "Satkania",
          "Sitakunda",
        ],
      },
      {
        name: "Comilla",
        thanas: [
          "Barura",
          "Brahmanpara",
          "Chandina",
          "Chauddagram",
          "Comilla Sadar",
          "Comilla Sadar Dakshin",
          "Daudkandi",
          "Debidwar",
          "Homna",
          "Laksam",
          "Meghna",
          "Monohorgonj",
          "Muradnagar",
          "Nangalkot",
          "Titas",
        ],
      },
      {
        name: "Cox's Bazar",
        thanas: [
          "Chakaria",
          "Cox's Bazar Sadar",
          "Cox’s Bazar Sadar",
          "Kutubdia",
          "Maheshkhali",
          "Pekua",
          "Ramu",
          "Teknaf",
          "Ukhia",
        ],
      },
      {
        name: "Feni",
        thanas: [
          "Chhagalnaiya",
          "Daganbhuiyan",
          "Feni Sadar",
          "Fulgazi",
          "Parshuram",
          "Sonagazi",
        ],
      },
      {
        name: "Khagrachhari",
        thanas: [
          "Dighinala",
          "Khagrachhari Sadar",
          "Lakshmichhari",
          "Mahalchhari",
          "Manikchhari",
          "Matiranga",
          "Panchhari",
          "Ramgarh",
        ],
      },
      {
        name: "Lakshmipur",
        thanas: [
          "Kamalnagar",
          "Lakshmipur Sadar",
          "Raipur",
          "Ramganj",
          "Ramgati",
        ],
      },
      {
        name: "Noakhali",
        thanas: [
          "Begumganj",
          "Chatkhil",
          "Companiganj",
          "Hatiya",
          "Kabirhat",
          "Noakhali Sadar",
          "Senbagh",
          "Subarnachar",
        ],
      },
      {
        name: "Rangamati",
        thanas: [
          "Baghaichhari",
          "Barkal",
          "Belaichhari",
          "Juraichhari",
          "Kaptai",
          "Kawkhali",
          "Langadu",
          "Naniarchar",
          "Rajasthali",
          "Rangamati Sadar",
        ],
      },
    ],
  },
  {
    name: "Dhaka",
    districts: [
      {
        name: "Dhaka",
        thanas: [
          "Adabor",
          "Badda",
          "Banani",
          "Bangshal",
          "Bhashantek",
          "Bhatara",
          "Biman Bandar",
          "Cantonment",
          "Chakbazar",
          "Dakshinkhan",
          "Darus Salam",
          "Demra",
          "Dhamrai",
          "Dhanmondi",
          "Dohar",
          "Gendaria",
          "Gulshan",
          "Hazaribagh",
          "Jatrabari",
          "Kafrul",
          "Kalabagan",
          "Kamrangirchar",
          "Keraniganj",
          "Khilgaon",
          "Khilkhet",
          "Kotwali",
          "Lalbagh",
          "Mirpur",
          "Mohammadpur",
          "Motijheel",
          "Mugda",
          "Nawabganj",
          "New Market",
          "Pallabi",
          "Paltan",
          "Ramna",
          "Rampura",
          "Rupnagar",
          "Sabujbagh",
          "Savar",
          "Shah Ali",
          "Shahbagh",
          "Shahjahanpur",
          "Sher-e-Bangla Nagar",
          "Shyampur",
          "Sutrapur",
          "Tejgaon",
          "Turag",
          "Uttara East",
          "Uttara West",
          "Uttarkhan",
          "Wari",
        ],
      },
      {
        name: "Faridpur",
        thanas: [
          "Alfadanga",
          "Bhanga",
          "Boalmari",
          "Charbhadrasan",
          "Faridpur Sadar",
          "Madhukhali",
          "Nagarkanda",
          "Sadarpur",
          "Saltha",
        ],
      },
      {
        name: "Gazipur",
        thanas: [
          "Basan",
          "Gachha",
          "Gazipur Sadar",
          "Joydebpur",
          "Kaliakair",
          "Kaliganj",
          "Kapasia",
          "Kashimpur",
          "Konabari",
          "Pubail",
          "Sreepur",
          "Tongi",
        ],
      },
      {
        name: "Gopalganj",
        thanas: [
          "Gopalganj Sadar",
          "Kashiani",
          "Kotalipara",
          "Muksudpur",
          "Tungipara",
        ],
      },
      {
        name: "Kishoreganj",
        thanas: [
          "Austagram",
          "Bajitpur",
          "Bhairab",
          "Hossainpur",
          "Itna",
          "Karimganj",
          "Katiadi",
          "Kishoreganj Sadar",
          "Kuliarchar",
          "Mithamain",
          "Nikli",
          "Pakundia",
          "Tarail",
        ],
      },
      {
        name: "Madaripur",
        thanas: [
          "Dasar",
          "Kalkini",
          "Madaripur Sadar",
          "Rajoir",
          "Shibchar",
        ],
      },
      {
        name: "Manikganj",
        thanas: [
          "Daulatpur",
          "Ghior",
          "Harirampur",
          "Manikganj Sadar",
          "Saturia",
          "Shibalaya",
          "Singair",
        ],
      },
      {
        name: "Munshiganj",
        thanas: [
          "Gazaria",
          "Lohajang",
          "Munshiganj Sadar",
          "Sirajdikhan",
          "Sreenagar",
          "Tongibari",
        ],
      },
      {
        name: "Narayanganj",
        thanas: [
          "Araihazar",
          "Bandar",
          "Fatullah",
          "Narayanganj Sadar",
          "Rupganj",
          "Siddhirganj",
          "Sonargaon",
        ],
      },
      {
        name: "Narsingdi",
        thanas: [
          "Belabo",
          "Monohardi",
          "Narsingdi Sadar",
          "Palash",
          "Raipura",
          "Shibpur",
        ],
      },
      {
        name: "Rajbari",
        thanas: [
          "Baliakandi",
          "Goalandaghat",
          "Kalukhali",
          "Pangsha",
          "Rajbari Sadar",
        ],
      },
      {
        name: "Shariatpur",
        thanas: [
          "Bhedarganj",
          "Damudya",
          "Gosairhat",
          "Naria",
          "Shariatpur Sadar",
          "Zajira",
        ],
      },
      {
        name: "Tangail",
        thanas: [
          "Basail",
          "Bhuapur",
          "Delduar",
          "Dhanbari",
          "Ghatail",
          "Gopalpur",
          "Kalihati",
          "Madhupur",
          "Mirzapur",
          "Nagarpur",
          "Sakhipur",
          "Tangail Sadar",
        ],
      },
    ],
  },
  {
    name: "Khulna",
    districts: [
      {
        name: "Bagerhat",
        thanas: [
          "Bagerhat Sadar",
          "Chitalmari",
          "Fakirhat",
          "Kachua",
          "Mollahat",
          "Mongla",
          "Morrelganj",
          "Rampal",
          "Sarankhola",
        ],
      },
      {
        name: "Chuadanga",
        thanas: [
          "Alamdanga",
          "Chuadanga Sadar",
          "Damurhuda",
          "Jibannagar",
        ],
      },
      {
        name: "Jashore",
        thanas: [
          "Abhaynagar",
          "Bagherpara",
          "Chaugachha",
          "Jashore Sadar",
          "Jhikargachha",
          "Keshabpur",
          "Manirampur",
          "Sharsha",
        ],
      },
      {
        name: "Jhenaidah",
        thanas: [
          "Harinakunda",
          "Jhenaidah Sadar",
          "Kaliganj",
          "Kotchandpur",
          "Maheshpur",
          "Shailkupa",
        ],
      },
      {
        name: "Khulna",
        thanas: [
          "Aranghata",
          "Batiaghata",
          "Dacope",
          "Daulatpur",
          "Dighalia",
          "Dumuria",
          "Harintana",
          "Khalishpur",
          "Khan Jahan Ali",
          "Khulna Kotwali",
          "Koyra",
          "Labanchara",
          "Paikgachha",
          "Phultala",
          "Rupsa",
          "Sonadanga",
          "Terokhada",
        ],
      },
      {
        name: "Kushtia",
        thanas: [
          "Bheramara",
          "Daulatpur",
          "Khoksa",
          "Kumarkhali",
          "Kushtia Sadar",
          "Mirpur",
        ],
      },
      {
        name: "Magura",
        thanas: [
          "Magura Sadar",
          "Mohammadpur",
          "Shalikha",
          "Sreepur",
        ],
      },
      {
        name: "Meherpur",
        thanas: [
          "Gangni",
          "Meherpur Sadar",
          "Mujibnagar",
        ],
      },
      {
        name: "Narail",
        thanas: [
          "Kalia",
          "Lohagara",
          "Narail Sadar",
        ],
      },
      {
        name: "Satkhira",
        thanas: [
          "Assasuni",
          "Debhata",
          "Kalaroa",
          "Kaliganj",
          "Satkhira Sadar",
          "Shyamnagar",
          "Tala",
        ],
      },
    ],
  },
  {
    name: "Mymensingh",
    districts: [
      {
        name: "Jamalpur",
        thanas: [
          "Bakshiganj",
          "Dewanganj",
          "Islampur",
          "Jamalpur Sadar",
          "Madarganj",
          "Melandaha",
          "Sarishabari",
        ],
      },
      {
        name: "Mymensingh",
        thanas: [
          "Bhaluka",
          "Dhobaura",
          "Fulbaria",
          "Gaffargaon",
          "Gauripur",
          "Haluaghat",
          "Ishwarganj",
          "Kotwali",
          "Muktagachha",
          "Mymensingh Sadar",
          "Nandail",
          "Phulpur",
          "Tarakanda",
          "Trishal",
        ],
      },
      {
        name: "Netrokona",
        thanas: [
          "Atpara",
          "Barhatta",
          "Durgapur",
          "Kalmakanda",
          "Kendua",
          "Khaliajuri",
          "Madan",
          "Mohanganj",
          "Netrokona Sadar",
          "Purbadhala",
        ],
      },
      {
        name: "Sherpur",
        thanas: [
          "Jhenaigati",
          "Nakla",
          "Nalitabari",
          "Sherpur Sadar",
          "Sreebardi",
        ],
      },
    ],
  },
  {
    name: "Rajshahi",
    districts: [
      {
        name: "Bogura",
        thanas: [
          "Adamdighi",
          "Bogura Sadar",
          "Dhunat",
          "Dhupchanchia",
          "Gabtali",
          "Kahaloo",
          "Nandigram",
          "Sariakandi",
          "Shajahanpur",
          "Sherpur",
          "Shibganj",
          "Sonatala",
        ],
      },
      {
        name: "Chapainawabganj",
        thanas: [
          "Bholahat",
          "Chapainawabganj Sadar",
          "Gomastapur",
          "Nachole",
          "Shibganj",
        ],
      },
      {
        name: "Joypurhat",
        thanas: [
          "Akkelpur",
          "Joypurhat Sadar",
          "Kalai",
          "Khetlal",
          "Panchbibi",
        ],
      },
      {
        name: "Naogaon",
        thanas: [
          "Atrai",
          "Badalgachhi",
          "Dhamoirhat",
          "Mahadebpur",
          "Manda",
          "Naogaon Sadar",
          "Niamatpur",
          "Patnitala",
          "Porsha",
          "Raninagar",
          "Sapahar",
        ],
      },
      {
        name: "Natore",
        thanas: [
          "Bagatipara",
          "Baraigram",
          "Gurudaspur",
          "Lalpur",
          "Naldanga",
          "Natore Sadar",
          "Singra",
        ],
      },
      {
        name: "Pabna",
        thanas: [
          "Atgharia",
          "Bera",
          "Bhangura",
          "Chatmohar",
          "Faridpur",
          "Ishwardi",
          "Pabna Sadar",
          "Santhia",
          "Sujanagar",
        ],
      },
      {
        name: "Rajshahi",
        thanas: [
          "Bagha",
          "Bagmara",
          "Boalia",
          "Chandrima",
          "Charghat",
          "Durgapur",
          "Godagari",
          "Kashiadanga",
          "Matihar",
          "Mohanpur",
          "Paba",
          "Puthia",
          "Rajpara",
          "Shah Makhdum",
          "Tanore",
        ],
      },
      {
        name: "Sirajganj",
        thanas: [
          "Belkuchi",
          "Chauhali",
          "Kamarkhanda",
          "Kazipur",
          "Raiganj",
          "Shahjadpur",
          "Sirajganj Sadar",
          "Tarash",
          "Ullapara",
        ],
      },
    ],
  },
  {
    name: "Rangpur",
    districts: [
      {
        name: "Dinajpur",
        thanas: [
          "Biral",
          "Birampur",
          "Birganj",
          "Bochaganj",
          "Chirirbandar",
          "Dinajpur Sadar",
          "Fulbari",
          "Ghoraghat",
          "Hakimpur",
          "Kaharole",
          "Khansama",
          "Nawabganj",
          "Parbatipur",
        ],
      },
      {
        name: "Gaibandha",
        thanas: [
          "Fulchhari",
          "Gaibandha Sadar",
          "Gobindaganj",
          "Palashbari",
          "Sadullapur",
          "Saghata",
          "Sundarganj",
        ],
      },
      {
        name: "Kurigram",
        thanas: [
          "Bhurungamari",
          "Char Rajibpur",
          "Chilmari",
          "Kurigram Sadar",
          "Nageshwari",
          "Phulbari",
          "Rajarhat",
          "Raomari",
          "Ulipur",
        ],
      },
      {
        name: "Lalmonirhat",
        thanas: [
          "Aditmari",
          "Hatibandha",
          "Kaliganj",
          "Lalmonirhat Sadar",
          "Patgram",
        ],
      },
      {
        name: "Nilphamari",
        thanas: [
          "Dimla",
          "Domar",
          "Jaldhaka",
          "Kishoreganj",
          "Nilphamari Sadar",
          "Saidpur",
        ],
      },
      {
        name: "Panchagarh",
        thanas: [
          "Atwari",
          "Boda",
          "Debiganj",
          "Panchagarh Sadar",
          "Tetulia",
        ],
      },
      {
        name: "Rangpur",
        thanas: [
          "Badarganj",
          "Gangachara",
          "Haragachh",
          "Kaunia",
          "Mahiganj",
          "Mithapukur",
          "Pirgachha",
          "Pirganj",
          "Rangpur Kotwali",
          "Rangpur Sadar",
          "Tajhat",
          "Taraganj",
        ],
      },
      {
        name: "Thakurgaon",
        thanas: [
          "Baliadangi",
          "Haripur",
          "Pirganj",
          "Ranisankail",
          "Thakurgaon Sadar",
        ],
      },
    ],
  },
  {
    name: "Sylhet",
    districts: [
      {
        name: "Habiganj",
        thanas: [
          "Ajmiriganj",
          "Bahubal",
          "Baniyachong",
          "Chunarughat",
          "Habiganj Sadar",
          "Lakhai",
          "Madhabpur",
          "Nabiganj",
          "Sayestaganj",
        ],
      },
      {
        name: "Moulvibazar",
        thanas: [
          "Barlekha",
          "Juri",
          "Kamalganj",
          "Kulaura",
          "Moulvibazar Sadar",
          "Rajnagar",
          "Sreemangal",
        ],
      },
      {
        name: "Sunamganj",
        thanas: [
          "Bishwamvarpur",
          "Chhatak",
          "Derai",
          "Dharampasha",
          "Dowarabazar",
          "Jagannathpur",
          "Jamalganj",
          "Shantiganj",
          "Sullah",
          "Sunamganj Sadar",
          "Tahirpur",
        ],
      },
      {
        name: "Sylhet",
        thanas: [
          "Airport",
          "Balaganj",
          "Beanibazar",
          "Bishwanath",
          "Companiganj",
          "Fenchuganj",
          "Golapganj",
          "Gowainghat",
          "Jaintiapur",
          "Jalalabad",
          "Kanaighat",
          "Moglabazar",
          "Osmani Nagar",
          "Shahporan",
          "Sylhet Kotwali",
          "Sylhet Sadar",
          "Zakiganj",
        ],
      },
    ],
  },
];

export const DIVISION_NAMES: string[] = BD_DIVISIONS.map(
  (division) => division.name,
);

export function districtsOf(division: string | undefined): BdDistrict[] {
  return (
    BD_DIVISIONS.find((candidate) => candidate.name === division)?.districts ??
    []
  );
}

export function thanasOf(
  division: string | undefined,
  district: string | undefined,
): string[] {
  return (
    districtsOf(division).find((candidate) => candidate.name === district)
      ?.thanas ?? []
  );
}

/** True only when the three names form a real division → district → thana path. */
export function isValidBdLocation(
  division: string | undefined,
  district: string | undefined,
  thana: string | undefined,
): boolean {
  if (!division || !district || !thana) return false;
  return thanasOf(division, district).includes(thana);
}
